language: ruby
rvm:
 - 2.0.0
install:
 - bundle install
 - gem build netdev.gemspec
 - gem build userpass.gemspec
 - gem install netdev
 - gem install userpass
 - gem contents netdev
 - gem contents userpass
