language: ruby
rvm:
 - 1.9.3
 - 2.0.0
 - 2.1.2
install:
 - bundle install
 - gem build netdev.gemspec
 - gem build userpass.gemspec
 - gem install netdev
 - gem install userpass
 - gem contents netdev
 - gem contents userpass
